### ISSUE TITLE
Headpose angles to screen coordinates

### ISSUE THREAD

**Issue by SaddamBInSyed** [denilDG/Computer-Pointer-Controller#1]
Hi @denilDG 

thanks for your work.

Since I don't have openvino setup in my win10 pc i could not able to try this repo.

but I am struggling to map my head pose angles ( from webcam video size: 300 * 200 ) to actual screen coordinates ( 1366 * 720 ).

I am using pyautoGUI lib.

could you please advise?

**Comment by denilgabani** [comment]
Hello @SaddamBInSyed 
I have used only the eye's direction to control the mouse pointer and for that, I have used the gaze estimation model with head pose roll output parameter value.

I have converted the output value of this gaze vector by converting the degree values to cartesian coordinates:
```
 def preprocess_output(self, outputs,hpa):
        '''
        Before feeding the output of this model to the next model,
        you might have to preprocess the output. This function is where you can do that.
        '''
        
        gaze_vector = outputs[self.output_names[0]].tolist()[0]
        #gaze_vector = gaze_vector / cv2.norm(gaze_vector)
        rollValue = hpa[2] #angle_r_fc output from HeadPoseEstimation model
        cosValue = math.cos(rollValue * math.pi / 180.0)
        sinValue = math.sin(rollValue * math.pi / 180.0)
        
        newx = gaze_vector[0] * cosValue + gaze_vector[1] * sinValue
        newy = -gaze_vector[0] *  sinValue+ gaze_vector[1] * cosValue
        return (newx,newy), gaze_vector 
```

This is written in gaze_estimation.py file and I gave this coordinates to MouseController class to control the mouse pointer.

I hope this will help you.
